site_name: Python for ArcGIS
site_author: Vojta Barták
repo_url: https://github.com/vojta-bartak/Python-for-ArcGIS-CZU-EN
theme: readthedocs
plugins: []
nav:
    - Home: index.md
    - Model Builder: 
        - 'Lesson 1: Model editting': 'Lesson 01 Model Builder I.md'
        - 'Lesson 2: User environment': 'Lesson 02 Model Builder II.md'
    - Python:
        - 'Lesson 3: Starting python': 'Lesson 03 Writing and running Python programs.md'
        - 'Lesson 4: Variables and data types': 'Lesson 04 Variables and data types'
        - 'Lesson 5: Loops and conditions': 'Lesson 05 Conditions and Loops.md'
        - 'Lesson 6: Inputs and random numbers': 'Lesson 06 Interactive inputs and random numbers.md'
        - 'Lesson 7: Directories and text files': 'Lesson 07 Directories and text files.md'
        - 'Lesson 8: Functions and modules': 'Lesson 08 Functions and modules.md'
        - 'Lekce 9: Třídy a objekty': 'Lekce 9 Třídy a objekty.md'
    - ArcPy:
        - 'Lesson 10: Running ArcPy tools': 'Lesson 10 Running ArcPy tools.md'
        - 'Lekce 11: Procházení a prohlížení geodat': 'Lekce 11 Procházení geodat a jejich vlastností pomocí balíčku ArcPy.md'
        - 'Lesson 12: Tool user interfaces': 'Lesson 12 Tool user interfaces.md'
        - 'Lesson 13: Attribute Operations': 'Lesson 13 Attribute Operations.md'
        - 'Lekce 15: Kurzory': 'Lekce 15 Procházení tabulek pomocí kurzorů.md'
        - 'Lekce 18: Rastrové analýzy': 'Lekce 18 Rastrové analýzy.md'
    - About me...: about_me.md
    - Tests and homeworks: tests_upload.md